# Generated by Django 5.0.6 on 2024-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_delete_notes_delete_users_remove_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
